### ISSUE TITLE
v1.4.0 checklist

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#119]
- [x] Rename milestone to version number
- [x] Add version in migration comment
- [x] Bump app version

**Builds:** 
- [x] Build and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows build
- [x] Test Linux build
- [x] Test OSX build

**Release:**
- [x] Create release on repository with correct version and tag
- [x] Add Windows binaries to release
- [x] Add Linux binaries to release
- [x] Add OSX binaries to release
- [x] Publish release

**Website:**
- [x] Update website versions
- [x] Merge website branch
- [x] Publish website on Firebase

**Distribution:**
- [x] Update homebrew cask
- [x] Update choco

**Misc:**
- [x] Close / update Github issues
- [x] Clean 'Next release' project
- [x] Spread the word!
