### ISSUE TITLE
v1.5.0 checklist

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#169]
- [x] Bump app version

**Builds:**
- [x] Build and sign Windows binary
- [x] Build Linux binaries (deb, rpm, snap, AppImage)
- [x] Build OSX binary (dmg)

**Tests:**
- [x] Test Windows binary
- [x] Test Linux binary(ies)
- [x] Test OSX binary

**Release:**
- [x] Create release on repository with correct version and tag
- [x] Add Windows binaries to release
- [x] Add Linux binaries to release
- [x] Add OSX binaries to release
- [x] Publish release

**Website:**
- [x] Update website versions
- [x] Publish website on Firebase

**Distribution:**
- [x] Update homebrew cask
- [x] Update Snap Store
- [x] Update choco

**Misc:**
- [x] Close / update Github issues
- [x] Clean 'Roadmap' project
- [x] Spread the word!
