### ISSUE TITLE
v1.0.0 checklist

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#42]
- [x] Bump app version

**Builds:** 
- [x] Build  and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows build
- [x] Test Linux build
- [x] Test OSX build

**Publish:**
- [x] Publish Windows binaries
- [x] Publish Linux binaries
- [x] Publish OSX binaries
- [x] Publish update file
- [x] Create release on repository
- [x] Merge website branch
- [x] publish website
- [x] merge wiki branch
- [x] Close / update Github issues
- [x] Spread the word!
  - [x] Plan posts on social networks
  - [x] Send newsletter
